### Домашнее задание №8. ###
**Дисперсионный анализ. Логистическая регрессия**

**1. Провести дисперсионный анализ для определения того, есть ли различия среднего роста среди взрослых футболистов, хоккеистов и штангистов. Даны значения роста в трех группах случайно выбранных спортсменов: Футболисты: 173, 175, 180, 178, 177, 185, 183, 182. Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180. Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170**

In [1]:
import numpy as np
y1 = np.array([173, 175, 180, 178, 177, 185, 183, 182])
y2 = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180])
y3 = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])
k = 3
n1 = len(y1)
n2 = len(y2)
n3 = len(y3)
n = n1 + n2 + n3


In [2]:
y1, y2, y3

(array([173, 175, 180, 178, 177, 185, 183, 182]),
 array([177, 179, 180, 188, 177, 172, 171, 184, 180]),
 array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170]))

In [3]:
n

28

In [4]:
print('Средний рост для каждой группы')
y1_mean = y1.mean()
y2_mean = y2.mean()
y3_mean = y3.mean()
print(f"Средний рост футболистов: {y1_mean}")
print(f"Средний рост хоккеистов: {y2_mean}")
print(f"Средний рост штангистов: {y3_mean}")

Средний рост для каждой группы
Средний рост футболистов: 179.125
Средний рост хоккеистов: 178.66666666666666
Средний рост штангистов: 172.72727272727272


Средний рост для каждой группы разнится.  Установим, что это отличие статистически значимо. Для этого сначала соберем

все значения заработных плат в один массив:

In [5]:
y_all = np.concatenate([y1, y2, y3])
y_all

array([173, 175, 180, 178, 177, 185, 183, 182, 177, 179, 180, 188, 177,
       172, 171, 184, 180, 172, 173, 169, 177, 166, 180, 178, 177, 172,
       166, 170])

In [6]:
y_mean = y_all.mean()
print(f"Найдем среднее по всем значениям: {y_mean}")

Найдем среднее по всем значениям: 176.46428571428572


In [7]:
s2 = np.sum((y_all - y_mean)**2)
print(f"Найдем сумму квадратов отклонений наблюдений от общего среднего:{s2}")

Найдем сумму квадратов отклонений наблюдений от общего среднего:830.9642857142854


In [8]:
sf2 = ((y1_mean - y_mean)**2) * n1 + ((y2_mean - y_mean)**2) * n2 + ((y3_mean - y_mean)**2) * n3
print(f"Cумма квадратов отклонений средних групповых значений от общего среднего:{sf2}")

Cумма квадратов отклонений средних групповых значений от общего среднего:253.9074675324678


In [9]:
so2 = 0
for item in y1:
    so2 += (item - y1.mean())**2
for item in y2:
    so2 += (item - y2.mean())**2
for item in y3:
    so2 += (item - y3.mean())**2
print(f"Остаточная сумма квадратов отклонений:{so2}")

Остаточная сумма квадратов отклонений:577.0568181818181


Проверим уравнение: $S^2 = S_F^2 + S_{ост}^2$

In [10]:
print(f"{s2} = {sf2 + so2}")

830.9642857142854 = 830.9642857142859


Найдем общую дисперсию:

In [11]:
sigma2_general = s2 / (n - 1)
sigma2_general

30.776455026455015

In [12]:
sigma2_f = sf2 / (k - 1)

print(f"Найдем факторную дисперсию:\n{sigma2_f}")

Найдем факторную дисперсию:
126.9537337662339


In [13]:
sigma2_residual = so2 / (n - k)

print(f"Найдем остаточную дисперсию:\n{sigma2_residual}")

Найдем остаточную дисперсию:
23.082272727272724


In [14]:
F_h = sigma2_f / sigma2_residual

print(f"Расчетаем значение критерия Фишера-Снедекора:\n{F_h}")

Расчетаем значение критерия Фишера-Снедекора:
5.500053450812599


Найдем значение $F_{крит}$ в таблице критических точек распределения Фишера-Снедекора для заданного уровня значимости $\alpha = 0.05$ и двух степеней свободы: 

$df_{межд} = k - 1 = 3 - 1 = 2$ и $df_{внутр} = n - k = 28 - 3 = 25$.

будет равно $F_{крит} = 3,38$

Так как $F_H > F_{крит}$, различие среднего роста в трех группах статистически значимо.

Вычислим эмпирическое корреляционное отношение $\eta^2$:

In [15]:
eta2 = sf2 / s2

print(f"Эмпирическое корреляционное отношение:\n{eta2}")

Эмпирическое корреляционное отношение:
0.30555761769498


Проверим наше расченое значение критерия Фишера-Снедекора с значением полученным с помощью автоматичиской функции для однофакторного анализа

In [16]:
from scipy import stats
stats.f_oneway(y1, y2, y3)

F_onewayResult(statistic=5.500053450812596, pvalue=0.010482206918698694)

**Ответ: После проверок  можно считать что мы правильно произели расчет. Различие среднего роста в трех группах статистически значимо. Различие среднего роста статистически значимо до уровня значимости не менее 0.010482206918698694.**